appName: "bpp-ev-charging"

log:
  level: debug
  destinations:
    - type: stdout
  contextKeys:
    - transaction_id
    - message_id
    - subscriber_id
    - module_id
    - parent_id

http:
  port: 8002
  timeout:
    read: 30
    write: 30
    idle: 30

pluginManager:
  root: /app/plugins

modules:
  - name: bppTxnReceiver
    path: /bpp/receiver/
    handler:
      type: std
      role: bpp
      subscriberId: uat-bpp-opci-adapter.ubc.nbsl.org.in
      httpClientConfig:
        maxIdleConns: 1000
        maxIdleConnsPerHost: 200
        idleConnTimeout: 300s
        responseHeaderTimeout: 5s
      plugins:
        registry:
          id: dediregistry
          config:
            url: http://api.testnet.beckn.one/dedi
            registryName: subscribers.beckn.one
            retry_max: 3
            retry_wait_min: 100ms
            retry_wait_max: 500ms
        keyManager:
          id: simplekeymanager
          config:
            networkParticipant: uat-bpp-opci-adapter.ubc.nbsl.org.in
            keyId: 76EU8AV7JusA4x7bLLTRLsiPJUmuFXgjoZggE3KV767ZKocKZX9WqH
            signingPrivateKey: EQoV5BnFliUdoYvs1jvA+B0Y/Ae2EUvdMldUasLbqb0=
            signingPublicKey: mmWTDIW17Hpmma/MS4tGhZZMb4DVBzj//zezIAJN+9k=
            encrPrivateKey: IFjVaPDBlfgzIqxgQOFcUzoUacWOGgt4NnRZ91kFTng=
            encrPublicKey: siU4GxSDZXunCX9BisipOK23chBUFZnM8vSPE3UdhG4=
        cache:
          id: cache
          config:
            addr: redis-onix-bpp:6379
        signValidator:
          id: signvalidator
        router:
          id: router
          config:
            routingConfig: /app/config/bpp_receiver_routing.yaml
        middleware:
          - id: reqpreprocessor
            config:
              contextKeys: transaction_id,message_id,parent_id
              role: bpp
      steps:
        - validateSign
        - addRoute

  - name: bppTxnCaller
    path: /bpp/caller/
    handler:
      type: std
      role: bpp
      subscriberId: uat-bpp-opci-adapter.ubc.nbsl.org.in
      httpClientConfig:
        maxIdleConns: 1000
        maxIdleConnsPerHost: 200
        idleConnTimeout: 300s
        responseHeaderTimeout: 5s
      plugins:
        registry:
          id: dediregistry
          config:
            url: http://api.testnet.beckn.one/dedi
            registryName: subscribers.beckn.one
            retry_max: 3
            retry_wait_min: 100ms
            retry_wait_max: 500ms
        keyManager:
          id: simplekeymanager
          config:
            networkParticipant: uat-bpp-opci-adapter.ubc.nbsl.org.in
            keyId: 76EU8AV7JusA4x7bLLTRLsiPJUmuFXgjoZggE3KV767ZKocKZX9WqH
            signingPrivateKey: EQoV5BnFliUdoYvs1jvA+B0Y/Ae2EUvdMldUasLbqb0=
            signingPublicKey: mmWTDIW17Hpmma/MS4tGhZZMb4DVBzj//zezIAJN+9k=
            encrPrivateKey: IFjVaPDBlfgzIqxgQOFcUzoUacWOGgt4NnRZ91kFTng=
            encrPublicKey: siU4GxSDZXunCX9BisipOK23chBUFZnM8vSPE3UdhG4=
        cache:
          id: cache
          config:
            addr: redis-onix-bpp:6379
        router:
          id: router
          config:
            routingConfig: /app/config/bpp_caller_routing.yaml
        signer:
          id: signer
        middleware:
          - id: reqpreprocessor
            config:
              contextKeys: transaction_id,message_id,parent_id
              role: bpp
      steps:
        - addRoute
        - sign
